# Generated by Django 3.0.6 on 2020-05-30 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clickcount',
            options={'ordering': ['link'], 'verbose_name': 'Link Tıklanma Sayısı', 'verbose_name_plural': 'Linklerin Günlük Tıklanma Sayısı'},
        ),
        migrations.AlterField(
            model_name='clickcount',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='link.Link', unique_for_date='date'),
        ),
        migrations.AlterField(
            model_name='link',
            name='hide_link',
            field=models.URLField(unique=True, verbose_name='Gizli/Yönlendirilmiş Link'),
        ),
    ]
