# Generated by Django 3.0.6 on 2020-06-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_link_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='hide_link',
            field=models.CharField(max_length=10, unique=True, verbose_name='Gizli/Yönlendirilmiş Link'),
        ),
    ]
