# Generated by Django 3.0.6 on 2020-06-04 08:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('link', '0005_auto_20200602_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['-created_at'], 'verbose_name': 'Link', 'verbose_name_plural': 'Linkler'},
        ),
        migrations.AlterField(
            model_name='link',
            name='exact_link',
            field=models.URLField(verbose_name='URL giriniz.'),
        ),
        migrations.AlterField(
            model_name='link',
            name='hide_link',
            field=models.CharField(max_length=255, unique=True, verbose_name='Gizli/Yönlendirilmiş Link'),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('owner', 'exact_link', 'hide_link')},
        ),
    ]
