# Generated by Django 3.0.6 on 2020-06-04 08:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('link', '0006_auto_20200604_0824'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('owner', 'exact_link')},
        ),
    ]
